# Generated by Django 2.2 on 2019-05-16 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('malina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
